language: php
php:
- 7.2
before_script:
#- composer install
script: echo 'none'
deploy:
  provider: heroku
  app: sesion6-travis-heroku
  on: master
  skip_cleanup: true
  api_key:
    secure: FN2bYU5BwwRpzWkkRJAXLw/2icPLjdR3bdSUjuW36tBt8Yqdd5fLSdnhyW4kpZ+zx2hdZle8FmRhPuqMzimpHAcbp1ShUSpYhSDayw/uy6mhlbVZDnr1yR/vLVwCUDENkHXYpqz4Ud7yBU9mwzkt8/Or8E/FjZeeYNyIEZCb6yXbYnFzFWpOvhlDf2iu0vwX3GdUhXK2Sz8NXA31Vpc11AoZKxSODxUIrQ35UqT1wn3AiFSygz3dNTLVyV9Ydgz2lJZ30h80mGpbXFyfmukayBcFUAdhmgvVW6p9c8KARBIeV7xSQey2w9UuvQa7sX5GtMAsVqTW82gM3G0arO/gnW3/oyD36f25CcW6cznSuM15cGZZFR0i2sEeY/8lb/Z9KGV3tdcDZO4HXZeANeYc8RG9OkMtCLe/lS9NTuRr/GQ9hC2CUyvcgecSauxa+IOKWbeVVyogIQ3v/ve7fvrANDawanxgN+U6yo9HJ89SIHl3TO1agIywX+JR7UNioYJiuoFPlEuWto2cLK0M4JIOpNgxKNNrXN5Ejz6RbdNrUBoYdW9VRijW2ePvcnmnIQFAX3sbgXqSNBUJm6YvAIClQyX/ivQ3NbsMBH4AO1gRK6M16B94yWahd0opQZSBEJzqr2CMotrjUxzzTmkT+CwQRlhbJGoUU+mJHtKdAP8dst4=
