language: php
php:
- 7.2
before_script:
#- composer install
script: echo 'none'
deploy:
  provider: heroku
  app: curso-github-cefire
  on: master
  skip_cleanup: true
  api_key:
    secure: RsG4ujCXYnXEq24W5czuG9rHXxlRh4yZClM1Nd1Sh/t3eUatU1K02Yq8GpqdOGHHU5MJutBQUeDQh81HC+vgO2sfzfiwHdW9DqX2culIQGMqYve5UoktZlJsC/0MVipfWDC+VISCsUgu+47D2qj+gnSaC+YwK8zArbG/JJYYOpReLRSVuWjyTI9Kj1Bl5KaKD6nleD+soLigHXKbHUaQtlKbm0scZg4po3yLudFfrAwNZZRRRWqJaYccy8EBeUmjxueOjTWpTV2TOkbZcnmu4fXdRAMMLZL89ikL327kAFnqteVDDKDeIiXtFHlFIsG8BLZbcINhtCMSbOsW6glR9W+SnbLC4qIosjnpeVtoX9gyZSxrf1d+X+jG8NDki4wCoh5lsrSLKi8Pk/V1+QKxKcAmS5oOPYWyINFv3Po1qmctrUzY7XOwS4H+zbzLWWYjdH+8fVu6pzjAo0vuKO6aEZMwv5nXWCFI92BpT9c2MQnKFgDXPbKxVIrKufaqWupbrQmA4LQca0h68gb4tFd3sgU0FQtsFI/LoSlFof6oOmun5Yig8DYMOjTY19Zsc53mSqHZ2wf/YAhSGjUA2G7RKytPdczeR3tbIh51rxRq687FUk8iEWARnD1uZDebFO6idHVLYwyO9DbvfZr7YlpuSQ/V69L6jOikxx4hCdGAhHM=
